# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d78761c3406f445beafd437809e3df6fe4d943b685237ed43ee6b404c7fefc06e395318ae7f5009a6b08ff5b3aa71a297e42b8a9c40ceb907238eec789ec7c9

test:
  secret_key_base: 81ca0e20f788fd1453df1fff7baba667f2d33ac8edcb6abad74df9ee923268c58b2448c6d9bcbe35d80e739138d013c8c8bdb2f4bf80143e916b1f5c987bb0a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
